# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateIntersectDialogBase(object):
    def setupUi(self, CreateIntersectDialogBase):
        CreateIntersectDialogBase.setObjectName("CreateIntersectDialogBase")
        CreateIntersectDialogBase.resize(575, 499)
        CreateIntersectDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        CreateIntersectDialogBase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        CreateIntersectDialogBase.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateIntersectDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableClickedWays = QtWidgets.QTableWidget(CreateIntersectDialogBase)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableClickedWays.setFont(font)
        self.tableClickedWays.setLineWidth(1)
        self.tableClickedWays.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableClickedWays.setDragEnabled(True)
        self.tableClickedWays.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableClickedWays.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableClickedWays.setGridStyle(QtCore.Qt.DotLine)
        self.tableClickedWays.setObjectName("tableClickedWays")
        self.tableClickedWays.setColumnCount(0)
        self.tableClickedWays.setRowCount(0)
        self.tableClickedWays.verticalHeader().setDefaultSectionSize(17)
        self.verticalLayout.addWidget(self.tableClickedWays)
        self.groupBox_filter = QtWidgets.QGroupBox(CreateIntersectDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_filter.sizePolicy().hasHeightForWidth())
        self.groupBox_filter.setSizePolicy(sizePolicy)
        self.groupBox_filter.setObjectName("groupBox_filter")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_filter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_filter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_filter)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget.setObjectName("listWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.listWidget)
        self.label = QtWidgets.QLabel(self.groupBox_filter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_filter)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_filter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_filter)
        self.spinBox.setMouseTracking(False)
        self.spinBox.setFrame(False)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setMaximum(100)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addWidget(self.groupBox_filter)
        self.button_box = QtWidgets.QDialogButtonBox(CreateIntersectDialogBase)
        self.button_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)
        self.label_8 = QtWidgets.QLabel(CreateIntersectDialogBase)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)

        self.retranslateUi(CreateIntersectDialogBase)
        self.button_box.accepted.connect(CreateIntersectDialogBase.accept)
        self.button_box.rejected.connect(CreateIntersectDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateIntersectDialogBase)

    def retranslateUi(self, CreateIntersectDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CreateIntersectDialogBase.setWindowTitle(_translate("CreateIntersectDialogBase", "Выберите маршрут"))
        self.tableClickedWays.setSortingEnabled(True)
        self.groupBox_filter.setTitle(_translate("CreateIntersectDialogBase", "Фильтр"))
        self.label_3.setText(_translate("CreateIntersectDialogBase", "Исключить:"))
        self.label.setText(_translate("CreateIntersectDialogBase", "Перевозчик: "))
        self.label_2.setText(_translate("CreateIntersectDialogBase", "Пересечение: "))
        self.spinBox.setSuffix(_translate("CreateIntersectDialogBase", "%"))
        self.label_8.setText(_translate("CreateIntersectDialogBase", "<html><head/><body><p><span style=\" color:#828282;\">2021 Zlatanov E. - Калининград</span></p></body></html>"))

